version: '3'
services:
  qb:
    build: .
    image: "bert"
    ports:
      - "4861:4861"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
    command: ["bash", "run.sh"]
  eval:
    image: "bert"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
      - ./:/eval
    command: [
      "python", "/eval/evaluate.py",
      "--curve-pkl", "/eval/curve_pipeline.pkl",
      "--wait", "10",
      "--hostname", "qb",
      "--norun-web",
      "--char_step_size", "60",
      "--retrieved_paragraphs_path", "data/qanta.test.paragraphs.2018.04.18.jsonl",
      "data/qanta.test.2018.04.18.json"
    ]
    depends_on:
      - "qb"
    environment:
      - "PYTHONUNBUFFERED=1"
